# Generated by Django 4.1.9 on 2023-05-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='FechaNacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='Nacionalidad',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='Sexo',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='Telefono',
            field=models.IntegerField(null=True),
        ),
    ]
