# Generated by Django 4.1.9 on 2023-05-19 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0002_alter_candidato_fechanacimiento_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Candidato',
        ),
    ]
