# Generated by Django 4.1.9 on 2023-05-19 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0003_delete_candidato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('DNI', models.CharField(max_length=9, null=True)),
                ('FechaNacimiento', models.DateField(null=True)),
                ('Sexo', models.CharField(max_length=20, null=True)),
                ('Nacionalidad', models.CharField(max_length=50, null=True)),
                ('Telefono', models.IntegerField(null=True)),
                ('Mail', models.CharField(max_length=150, null=True)),
                ('ImgDNI', models.CharField(max_length=500, null=True)),
                ('ImgSIP', models.CharField(max_length=500, null=True)),
                ('Municipio', models.CharField(max_length=100, null=True)),
                ('CP', models.IntegerField(null=True)),
                ('Provincia', models.CharField(max_length=75, null=True)),
                ('EntidadBancaria', models.CharField(max_length=200, null=True)),
                ('IBAN', models.CharField(max_length=24, null=True)),
                ('Domicilio', models.CharField(max_length=300, null=True)),
                ('OfertaID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webApp.oferta')),
                ('PeticionID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webApp.peticion')),
            ],
        ),
    ]
