# Generated by Django 4.1.9 on 2023-05-23 11:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0004_candidato'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='Estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Registrado', 'Registrado')], default='Pendiente', max_length=10),
        ),
        migrations.AddField(
            model_name='candidato',
            name='FechaRegistro',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
