# Generated by Django 4.1.9 on 2023-05-26 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0005_candidato_estado_candidato_fecharegistro'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='ultima_entrada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webApp.entradaoferta'),
        ),
    ]
