# Generated by Django 4.1.9 on 2023-05-26 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0006_oferta_ultima_entrada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta',
            name='ultima_entrada',
        ),
    ]
