# Generated by Django 4.1.9 on 2023-05-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0007_remove_oferta_ultima_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='Estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=8),
        ),
        migrations.AddField(
            model_name='oferta',
            name='lastUpdate',
            field=models.DateField(null=True),
        ),
    ]
