# Generated by Django 4.1.9 on 2023-05-30 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0008_oferta_estado_oferta_lastupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscriptores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=254)),
                ('Oferta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webApp.oferta')),
            ],
        ),
    ]
