# Generated by Django 4.1.9 on 2023-06-01 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0010_registro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='Observaciones',
        ),
        migrations.AlterField(
            model_name='suscriptores',
            name='Oferta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webApp.oferta'),
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.TextField()),
                ('Fecha', models.DateField()),
                ('Oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webApp.oferta')),
            ],
        ),
    ]
