# Generated by Django 4.1.9 on 2023-06-01 14:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0011_remove_registro_observaciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='FechaIni',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
