# Generated by Django 4.1.9 on 2023-06-01 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0012_registro_fechaini'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='Oferta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webApp.oferta'),
            preserve_default=False,
        ),
    ]
