# Generated by Django 4.1.9 on 2023-06-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0013_registro_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='Procesada',
            field=models.CharField(choices=[('No', 'No'), ('Si', 'Si')], default='No', max_length=2),
        ),
    ]
