# Generated by Django 4.1.9 on 2023-06-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0014_registro_procesada'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscriptores',
            name='tlf',
            field=models.IntegerField(default=1, max_length=9),
            preserve_default=False,
        ),
    ]
