# Generated by Django 4.1.9 on 2023-06-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0015_suscriptores_tlf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='Procesada',
            new_name='ProcesadaMail',
        ),
        migrations.AddField(
            model_name='registro',
            name='ProcesadaTlf',
            field=models.CharField(choices=[('No', 'No'), ('Si', 'Si')], default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='suscriptores',
            name='tlf',
            field=models.IntegerField(),
        ),
    ]
