# Generated by Django 4.1.9 on 2023-06-16 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0016_rename_procesada_registro_procesadamail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='ProcesadaMail',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='ProcesadaTlf',
        ),
    ]
