# Generated by Django 4.1.9 on 2023-06-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0019_comunicado_empleado_entradas_salidas_evolucion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatisfacionSeleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Definicion', models.CharField(max_length=75)),
                ('Grado', models.CharField(choices=[('Riguroso', 'Riguroso'), ('Útil', 'Útil'), ('Ameno', 'Ameno'), ('Transparente', 'Transparente'), ('Profesional', 'Profesional'), ('Técnico', 'Técnico'), ('Largo', 'Largo'), ('Ágil', 'Ágil')], default='Riguroso', max_length=12)),
                ('Respuesta', models.CharField(choices=[('Poco', 'Poco'), ('Algo', 'Algo'), ('Bastante', 'Bastante'), ('Totalmente', 'Totalmente')], default='Poco', max_length=10)),
                ('Mejora', models.CharField(max_length=500)),
                ('Valores', models.CharField(choices=[('No lo recuerdo', 'No lo recuerdo'), ('No', 'No'), ('Lo mencionaron pero no lo explicaron al detalle', 'Lo mencionaron pero no lo explicaron al detalle'), ('Sí, con mucho detalle', 'Sí, con mucho detalle'), ('Sí, con algo de detalle', 'Sí, con algo de detalle')], default='No lo recuerdo', max_length=200)),
                ('Expectativas', models.CharField(choices=[('No lo recuerdo', 'No lo recuerdo'), ('No', 'No'), ('Lo mencionaron pero no lo explicaron al detalle', 'Lo mencionaron pero no lo explicaron al detalle'), ('Sí, con mucho detalle', 'Sí, con mucho detalle'), ('Sí, con algo de detalle', 'Sí, con algo de detalle')], default='No lo recuerdo', max_length=200)),
                ('Condiciones', models.CharField(choices=[('No lo recuerdo', 'No lo recuerdo'), ('No', 'No'), ('Lo mencionaron pero no lo explicaron al detalle', 'Lo mencionaron pero no lo explicaron al detalle'), ('Sí, con mucho detalle', 'Sí, con mucho detalle'), ('Sí, con algo de detalle', 'Sí, con algo de detalle')], default='No lo recuerdo', max_length=200)),
                ('Utilidad', models.IntegerField()),
                ('MotivoAceptacion', models.CharField(max_length=500)),
                ('Centro', models.CharField(max_length=15)),
                ('Expetiencia', models.CharField(max_length=50)),
                ('FechaEntrevista', models.DateField()),
            ],
        ),
    ]
