# Generated by Django 4.2.2 on 2023-07-10 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0020_satisfacionseleccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatisfaccionBienvenida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(choices=[('15 dias', '15 dias'), ('45 dias', '45 dias')], default='15 dias', max_length=10)),
                ('Familiar', models.CharField(choices=[('Poco', 'Poco'), ('Algo', 'Algo'), ('Bastante', 'Bastante'), ('Totalmente', 'Totalmente')], default='Poco', max_length=10)),
                ('Util', models.CharField(choices=[('Poco', 'Poco'), ('Algo', 'Algo'), ('Bastante', 'Bastante'), ('Totalmente', 'Totalmente')], default='Poco', max_length=10)),
                ('Motivante', models.CharField(choices=[('Poco', 'Poco'), ('Algo', 'Algo'), ('Bastante', 'Bastante'), ('Totalmente', 'Totalmente')], default='Poco', max_length=10)),
                ('Explicacion_resp', models.CharField(choices=[('Poco', 'Poco'), ('Algo', 'Algo'), ('Bastante', 'Bastante'), ('Totalmente', 'Totalmente')], default='Poco', max_length=10)),
                ('Ayuda_resp', models.CharField(choices=[('Poco', 'Poco'), ('Algo', 'Algo'), ('Bastante', 'Bastante'), ('Totalmente', 'Totalmente')], default='Poco', max_length=10)),
                ('Interes_resp', models.CharField(choices=[('Poco', 'Poco'), ('Algo', 'Algo'), ('Bastante', 'Bastante'), ('Totalmente', 'Totalmente')], default='Poco', max_length=10)),
                ('Explicacion_comp', models.CharField(choices=[('Poco', 'Poco'), ('Algo', 'Algo'), ('Bastante', 'Bastante'), ('Totalmente', 'Totalmente')], default='Poco', max_length=10)),
                ('Ayuda_comp', models.CharField(choices=[('Poco', 'Poco'), ('Algo', 'Algo'), ('Bastante', 'Bastante'), ('Totalmente', 'Totalmente')], default='Poco', max_length=10)),
                ('Interes_comp', models.CharField(choices=[('Poco', 'Poco'), ('Algo', 'Algo'), ('Bastante', 'Bastante'), ('Totalmente', 'Totalmente')], default='Poco', max_length=10)),
                ('Cultura', models.CharField(max_length=300)),
                ('EntregaRopa', models.CharField(max_length=300)),
                ('ValoraRopa', models.CharField(max_length=300, null=True)),
                ('Puesto_exp', models.CharField(max_length=300)),
                ('Instalaciones', models.CharField(max_length=2)),
                ('Adaptacion_org', models.IntegerField()),
                ('Adaptacion_puesto', models.IntegerField()),
                ('Utilidad_puntuacion', models.IntegerField()),
                ('Dificultades', models.TextField(null=True)),
                ('Centro', models.CharField(max_length=200)),
                ('Experiencia', models.CharField(max_length=300)),
                ('FechaInc', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='satisfacionseleccion',
            name='Grado',
        ),
        migrations.RemoveField(
            model_name='satisfacionseleccion',
            name='Respuesta',
        ),
        migrations.AddField(
            model_name='satisfacionseleccion',
            name='Agil',
            field=models.CharField(choices=[('Poco', 'Poco'), ('Algo', 'Algo'), ('Bastante', 'Bastante'), ('Totalmente', 'Totalmente')], default='Poco', max_length=10),
        ),
        migrations.AddField(
            model_name='satisfacionseleccion',
            name='Ameno',
            field=models.CharField(choices=[('Poco', 'Poco'), ('Algo', 'Algo'), ('Bastante', 'Bastante'), ('Totalmente', 'Totalmente')], default='Poco', max_length=10),
        ),
        migrations.AddField(
            model_name='satisfacionseleccion',
            name='Largo',
            field=models.CharField(choices=[('Poco', 'Poco'), ('Algo', 'Algo'), ('Bastante', 'Bastante'), ('Totalmente', 'Totalmente')], default='Poco', max_length=10),
        ),
        migrations.AddField(
            model_name='satisfacionseleccion',
            name='Profesional',
            field=models.CharField(choices=[('Poco', 'Poco'), ('Algo', 'Algo'), ('Bastante', 'Bastante'), ('Totalmente', 'Totalmente')], default='Poco', max_length=10),
        ),
        migrations.AddField(
            model_name='satisfacionseleccion',
            name='Riguroso',
            field=models.CharField(choices=[('Poco', 'Poco'), ('Algo', 'Algo'), ('Bastante', 'Bastante'), ('Totalmente', 'Totalmente')], default='Poco', max_length=10),
        ),
        migrations.AddField(
            model_name='satisfacionseleccion',
            name='Tecnico',
            field=models.CharField(choices=[('Poco', 'Poco'), ('Algo', 'Algo'), ('Bastante', 'Bastante'), ('Totalmente', 'Totalmente')], default='Poco', max_length=10),
        ),
        migrations.AddField(
            model_name='satisfacionseleccion',
            name='Transparente',
            field=models.CharField(choices=[('Poco', 'Poco'), ('Algo', 'Algo'), ('Bastante', 'Bastante'), ('Totalmente', 'Totalmente')], default='Poco', max_length=10),
        ),
        migrations.AddField(
            model_name='satisfacionseleccion',
            name='Util',
            field=models.CharField(choices=[('Poco', 'Poco'), ('Algo', 'Algo'), ('Bastante', 'Bastante'), ('Totalmente', 'Totalmente')], default='Poco', max_length=10),
        ),
        migrations.CreateModel(
            name='Desvinculaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titular', models.CharField(max_length=100)),
                ('TresPalabras', models.CharField(max_length=150)),
                ('SituacionPositiva', models.CharField(max_length=300)),
                ('Mejora', models.TextField()),
                ('SituacionNegativa', models.CharField(max_length=300)),
                ('MotivosAbandono', models.CharField(max_length=350)),
                ('Propuesta', models.CharField(max_length=350)),
                ('Recomendacion', models.IntegerField()),
                ('ES', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webApp.entradas_salidas')),
            ],
        ),
    ]
