# Generated by Django 4.1.9 on 2023-07-13 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0021_satisfaccionbienvenida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observacion',
            name='Oferta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webApp.oferta'),
        ),
    ]
