# Generated by Django 4.1.9 on 2023-07-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0023_peticion_contratados_peticion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peticion',
            name='Contratados',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
