# Generated by Django 4.1.9 on 2023-07-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0024_alter_peticion_contratados'),
    ]

    operations = [
        migrations.AddField(
            model_name='peticion',
            name='Validado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='peticion',
            name='Estado',
            field=models.CharField(choices=[('Abierta', 'Abierta'), ('Cerrada', 'Cerrada')], default='Abierta', max_length=10),
        ),
    ]
