# Generated by Django 4.1.9 on 2023-07-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0025_peticion_validado_alter_peticion_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='ImgDNI',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='ImgSIP',
        ),
        migrations.AddField(
            model_name='candidato',
            name='Categoria',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='Centro',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='Convenio',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='SBA',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='SIP',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='Seccion',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='Sociedad',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
