# Generated by Django 4.1.9 on 2023-07-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0026_remove_candidato_imgdni_remove_candidato_imgsip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='TurnoInicial',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
