# Generated by Django 4.1.9 on 2023-07-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0027_candidato_turnoinicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='CentroComp',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
