# Generated by Django 4.1.9 on 2023-08-21 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0029_peticion_estadovalidacion_peticion_motivodenegado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peticion',
            old_name='MotivoDenegado',
            new_name='EstadoMotivo',
        ),
    ]
