# Generated by Django 4.1.9 on 2023-08-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0030_rename_motivodenegado_peticion_estadomotivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peticion',
            name='EstadoValidacion',
            field=models.CharField(choices=[('Aprobada', 'Aprobada'), ('Denegada', 'Denegada')], max_length=8, null=True),
        ),
    ]
