# Generated by Django 4.1.9 on 2023-10-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0032_alter_candidato_sip'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='Horas',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='Jornada',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
