# Generated by Django 4.1.9 on 2023-10-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0033_candidato_horas_candidato_jornada'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='Binvenida',
            field=models.BooleanField(null=True),
        ),
    ]
