# Generated by Django 4.1.9 on 2023-10-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0034_candidato_binvenida'),
    ]

    operations = [
        migrations.AddField(
            model_name='peticion',
            name='Comentarios',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='peticion',
            name='FechaIncEstimada',
            field=models.DateField(null=True),
        ),
    ]
