# Generated by Django 4.1.9 on 2023-10-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0035_peticion_comentarios_peticion_fechaincestimada'),
    ]

    operations = [
        migrations.AddField(
            model_name='peticion',
            name='FechaIncRevisada',
            field=models.DateField(null=True),
        ),
    ]
