# Generated by Django 4.1.9 on 2023-10-24 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0036_peticion_fechaincrevisada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidato',
            old_name='Binvenida',
            new_name='Bienvenida',
        ),
    ]
