# Generated by Django 4.1.9 on 2023-11-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0037_rename_binvenida_candidato_bienvenida'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='TallaChaqueta',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='M', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='TallaPantalon',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='M', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='TallaPolo',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='M', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='TallaZapatos',
            field=models.IntegerField(null=True),
        ),
    ]
