# Generated by Django 4.1.9 on 2023-11-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0038_candidato_tallachaqueta_candidato_tallapantalon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='TallaChaqueta',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], default='M', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='TallaPantalon',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], default='M', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='TallaPolo',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], default='M', max_length=4, null=True),
        ),
    ]
