# Generated by Django 5.0.3 on 2024-04-03 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0040_candidato_horasextra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paso',
            name='Oferta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='webApp.oferta'),
        ),
    ]
