# Generated by Django 5.0.3 on 2024-04-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0041_alter_paso_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='CategoriaSage',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
