# Generated by Django 5.0.3 on 2024-10-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0042_candidato_categoriasage'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='AreaOutlook',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='PuestoOutlook',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
